### PR TITLE
Adding the IS-05 extended schemas and examples

### PR DESCRIPTION
**Pull request by mjeras**
Andrew, could you please check if this is ok. Sender and receiver schemas are overridden and basic samples  are provided...

### CODE REVIEW

**Review by andrewbonney — COMMENTED** [review]
Thanks Miroslav. That looks good to me.

Is there any reason for the defaults on the Receiver side? I'd have thought if anything you may wish the default to be 'null' to represent an uninitialised state. If that's the case, the 'type' for each would need to be changed to: 'type': ['string', 'null']

**Comment by mjeras** [comment]
I though it would be good to specify the uninitialized state and I set it to auto which would mean "go and figure it out from the registry", although this would imply additional complexity on the receiving end as it would require drilling down to the source. Given that your base declarations allow null and don't have a default, I'll change the type to allow for nulls.

**Comment by mjeras** [comment]
Andrew, could you please check the latest change?

**Comment by andrewbonney** [comment]
Your nulls in the 'type' field will need to have quotes around them in order to be valid. It may also be worth doing the same on the Sender side.

**Comment by mjeras** [comment]
Thanks for spotting this - I did it in a hurry and forgot to run the validation tests, it should be fixed now.

I didn't do it on the sender side as we are specifying the sender has to expose those and those are essentially read-only at the sender side (unlike an multicast address for RTP, control system isn't expected to set the API URL or the connected source's ID). I guess the same would apply to the broker_topic and websockets URL...
Is there another reason why nulls would have to be specified?

**Comment by andrewbonney** [comment]
It's purely about an uninitialised state. If the Sender simply hasn't been configured yet but wishes to expose itself in order to permit configuration, then null must be an allowed value.

**Comment by mjeras** [comment]
In my opinion, it wouldn't be according to the specification not to have the API URL and a connected source known before starting a sender. Again, this is not something that would be configurable from the outside world, it is just the information for the control system so it can pass it on when connecting using IS-05.

**Comment by andrewbonney** [comment]
I'm happy to leave this decision up to you. I don't personally see a downside in permitting nulls, but equally I don't have a problem with this approach.

**Pull request merged**
