### PR TITLE
Fix image typos

### LINKED ISSUE #49: Little typos in images
(Originally https://github.com/AMWA-TV/nmos-event-tally/issues/40#issuecomment-493480067...)

There's a little typo in [event-types-capability-management.png](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0.x/docs/images/event-types-capability-management.png) of 'Celcius' instead of 'Celsius' repeated a few times. We've also now settled on `number/temperature` in the examples rather than `number/Temperature` so I'd like to change that, and `number/Pressure` similarly.

@cristian-recoseanu Were the images produced with something like https://www.draw.io/ so they can easily be regenerated by anyone? (Draw.io embeds the editable graphic objects/text/etc. into a PNG extension, so the PNG can be edited again without having to store a separate file.)

### PR DESCRIPTION
**Pull request by garethsb**
Import original Visio diagram into https://www.draw.io/, match recent changes to event types docs, and export to PNG with embedded diagram info to allow subsequent editing.

Resolves #49.

### CODE REVIEW

**Comment by cristian-recoseanu** [comment]
Looks good @garethsb-sony 
Thanks!

**Review by cristian-recoseanu — APPROVED** [review]
Looks good! Thank you for doing the importing of the original Visio and applying the corrections.

**Comment by garethsb** [comment]
No problem, @cristian-recoseanu, thanks for your help. If you come across the Visio diagrams for the other two images, we could do the same thing for those in the future.

**Review by mjeras — APPROVED** [review]
LGTM

**Pull request merged**
