### PR TITLE
Rename example files without spec version number

### PR DESCRIPTION
**Pull request by garethsb**
… to simplify comparison between version branches in the future (see https://github.com/AMWA-TV/nmos-discovery-registration/commit/8a00534a1fb8a5f89d6404f99aa4483209963e78 and https://github.com/AMWA-TV/nmos-device-connection-management/commit/1d21176ccbd165d2f6f28fc2db2b0c23c974bf06 for precedent), and delete 'eventsapi' from the filename of command and message examples.

### CODE REVIEW

**Review by andrewbonney — COMMENTED** [review]
LGTM. I'm assuming many of the example files aren't referenced anywhere?

**Comment by garethsb** [comment]
Yes, that does appear to be the case. We could add the additional examples for the `/type` and `/state` endpoints in the RAML, but I didn't do that here. The example message and command files could be referenced from the docs, but there are embedded examples in most places already.

**Review by mjeras — APPROVED** [review]
Looks good to me, do we have to be careful when to do the merge to avoid the conflicts? (given files were renamed)

**Comment by garethsb** [comment]
> Looks good to me, do we have to be careful when to do the merge to avoid the conflicts? (given files were renamed)

ASAP? 😉

Since it's only the example files which only see infrequent editing and very few of which are referenced currently, it's not hugely urgent, but certainly better to do for a v1.0.1, so that a rebranched v1.1-dev (if we go that way) and future version bumps show simpler diffs.

**Pull request merged**
