### PR TITLE
Documentation changes

### PR DESCRIPTION
**Pull request by cristian-recoseanu**
Many documentation changes which include feedback received in Github issues and via email.

### CODE REVIEW

**Review by andrewbonney — COMMENTED** [review]
Thanks Cristian, this seems to address the vast majority of the items in my issue. Just a few notes:

* Item 4 in my issue doesn't appear to have been addressed
* For item 14, whilst the CORS recommendations have been copied over, other docs such as the trailing slash policy have not. I'd consider adding this too and have a read of section 2 of IS-04 (or IS-05)'s docs for anything else which might be relevant. I'd recommend pulling these from the latest -dev branch to catch any recent updates.
* In 4.0 there's a minor error in the MQTT receiver transport parameters - source_host is listed twice.

**Comment by cristian-recoseanu** [comment]
Hi Andrew,

Your item 4 should be addressed in 6.0. Event and tally rest api - subsection **4. Type definition changes**

Item 14 - I understand. My preferred way was to mention how a url should be formated everywhere a URL is mentioned. This way you don't run into issues regarding redirects. I understand why IS-05 did that but I can't say I support redirects being the best solution. As we have seen in the workshops we had issues with implementers issuing multiple redirects with some of them being invalid. I think that is one example of "unintended consequences".

Thank you, I fixed the error related to the source_host appearing twice.

**Comment by andrewbonney** [comment]
Thanks Cristian.

On 14, I'm less concerned about redirects and more about what the 'authoritative' URL is (ie. the one you get a 2XX from rather than a 3XX). The trailing slash policy is in place more to indicate in a single place which the authoritative URL is for every resource. Redirects are intended to be more of a 'nice to have' to help with navigation using a web browser. As such the most important bits of the policy are:

> * For consistency and in order to adhere to how these APIs are specified in RAML, the 'primary' path for every resource has the trailing slash omitted.

This one is the key common ground

> * Clients performing requests using these (ie. PUT/PATCH/DELETE etc) methods MUST use URLs with no trailing slash present.

This one avoids a common error case where people try to POST/PATCH to the wrong path, but receive a 30X redirect in error followed by a 200. This gets interpreted as a success when in reality they've been redirected to a GET method.

I can only comment, so if you feel you need to have a different policy then that's your choice. The potential issue for the future is that this could make this API inconsistent with the others. As such it may make it incompatible with test suites (see https://github.com/bbc/nmos-testing which gives you some tests for free) and future efforts to try and refactor common API documentation into a separate specification.

**Comment by cristian-recoseanu** [comment]
Thanks Andrew,

I have to admit I read that bit but it wasn't clear to me what the "primary" path is.

Is that the origin href defined in the controls array?

**Comment by andrewbonney** [comment]
The recommendation is more about how the API's paths are implemented rather than how they're advertised in an 'href'.

Looking at the RAML (for IS-04), I could choose to implement any path in one of two ways, for example:
* /x-nmos/node/v1.2/self
Or
* /x-nmos/node/v1.2/self/

If I choose to implement one of these paths rather than both, then a client requesting the other one will receive a 404.

The recommendation is about establishing common ground between implementations such that everyone is required to implement '/x-nmos/node/v1.2/self' as the 'primary' path (ie. the one that gives you a 200 response code rather than a 30X). If '/x-nmos/node/v1.2/self/' is also implemented, this can then be a 30X to the non-trailing slash version, but not the other way around.

**Comment by cristian-recoseanu** [comment]
Hi Andrew,

I understand that a bit more now. Looking at it I think our comments are complementary.
My comments were meant more to define clearly what templates the URLs need to follow in order for the control system and the receiver to automatically make sense of them.

Your comment is more about a generic common ground about how to define your API and what the default expectation is.

I will see if I can integrate that section in the documentation.

**Comment by andrewbonney** [comment]
Sounds good, thanks!

**Comment by cristian-recoseanu** [comment]
Hi @andrewbonney 
I have included two subsections about CORS and trailing slashes in _6.0. Event and tally rest api_

Is that suitable and sufficient?

**Comment by andrewbonney** [comment]
That looks better. A minor note but the CORS advice has been updated slightly in the '-dev' branches of IS-04/05. You may wish to re-copy that section from there: https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3-dev/docs/2.3.%20APIs%20-%20Server%20Side%20Implementation%20Notes.md

**Comment by cristian-recoseanu** [comment]
> That looks better. A minor note but the CORS advice has been updated slightly in the '-dev' branches of IS-04/05. You may wish to re-copy that section from there: https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3-dev/docs/2.3.%20APIs%20-%20Server%20Side%20Implementation%20Notes.md

Ok thanks. That's done.

**Review by mjeras — APPROVED** [review]

**Pull request merged**
